version: "3.8"

services:
  frontend:
    build: ./frontend
    container_name: languages-frontend
    restart: unless-stopped
    ports:
      - "192.168.131.134:3007:4173"

  backend:
    build: ./backend
    container_name: languages-backend
    restart: unless-stopped
    ports:
      - "192.168.131.134:30071:3001"
    volumes:
      - ../../project-data/languages/data:/app/data
    env_file:
      - .env
