version: "3.8"
services:
  frontend:
    build: ./frontend
    container_name: arcade-frontend
    restart: unless-stopped
    ports:
      - "127.0.0.1:3003:3000"
    depends_on:
      - backend

  backend:
    build: ./backend
    container_name: arcade-backend
    restart: unless-stopped
    volumes:
      - ../../project-data/arcade/data:/app/data
    ports:
      - "127.0.0.1:30031:3000"
